# Generated by Django 3.2.8 on 2021-11-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutriscore', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'inconnu')], default='F', max_length=1)),
                ('energy_unit', models.CharField(choices=[('kJ', 'kJ'), ('kcal', 'kcal')], default='kcal', max_length=6)),
                ('energy_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('carbohydrates_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('sugars_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('fat_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('saturated_fat_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('fiber_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('proteins_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('salt_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('sodium_100g', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('off_link', models.CharField(max_length=1024)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('in_users_favourites', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
