# Generated by Django 3.2.8 on 2021-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_img_link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='off_thumb_link',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
