# Generated by Django 3.2.8 on 2021-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211118_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='energy_100g',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
